### ISSUE TITLE
Cheers, exactly what i was looking for, or thinking about making !

### ISSUE THREAD

**Issue by hayden-t** [cody82/open-hardware-monitor#1]
found your fork in google, and i almost thought about doing it myself as openhardware monitor has all the stuff i want, but i dont want to have to run another program to on top of that just to pipe its data to serial. 

im using it on arduino and only need raw data, i found where you spec what and how to send the serial data and am editing that now

the only thing left would be to let you select in the gui what you want to send or not, which ill try and do to avoid the need to recompile.

**Comment by hayden-t** [comment]
you can see my project page here: https://hackaday.io/project/10629-pc-analog-panel-meters-w-arduino

**Comment by cody82** [comment]
Great work!
